select*from customer
--what is total revenue generated by male vs female customer.
select gender,sum(purchase_amount) as revenue
from customer
group by gender
--which customer used discount but still spent more than avg purchase amount
select customer_id,gender,purchase_amount from customer
where discount_applied='Yes' and  purchase_amount>=(
select avg(purchase_amount)
from customer
)


--which are the top 5 product with the highest avg rating review
select item_purchased,ROUND(avg(review_rating::numeric),2)
from customer
group by item_purchased
order by avg(review_rating)desc
limit 5

--compare avg purchase_amount for standard and express shipping
select shipping_type,ROUND(avg(purchase_amount),2)
from customer
where shipping_type in('Express','Standard')
group by shipping_type

--Do subscribe customer spend more --compare 
--avg spend and total revenue betn subscriber and non subscriber

select subscription_status,count(customer_id) as total_customer,ROUND(avg(purchase_amount),2) as average_spend,sum(purchase_amount) as total_revenue
from customer
group by  subscription_status


--Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(
           100 * SUM(
               CASE
                   WHEN discount_applied = 'Yes' THEN 1
                   ELSE 0
               END
           ) / COUNT(*),
           2
       ) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

--Segment customers into New, Returning, and Loyal
--based on their previous purchases and show count of each segment

WITH customer_type AS (
    SELECT customer_id,
           previous_purchases,
           CASE
               WHEN previous_purchases = 1 THEN 'New'
               WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
               ELSE 'Loyal'
           END AS customer_segment
    FROM customer
)

SELECT customer_segment,
       COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment;


--what are the top 3 purchased product within each category
WITH ranked_products AS (
    SELECT
        category,
        item_purchased,
        COUNT(item_purchased) AS ip,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(item_purchased) DESC
        ) AS rn
    FROM customer
    GROUP BY category, item_purchased
)
SELECT
    category,
    item_purchased,
    ip
FROM ranked_products
WHERE rn <= 3
ORDER BY category ASC, ip DESC;



select category,item_purchased,
count(item_purchased) as ip
from customer
group by category,item_purchased
order by category asc,ip desc

--Are customers who are repeat buyers 
--(more than 5 previous purchases) also likely to subscribe?
SELECT
    subscription_status,
    COUNT(customer_id) AS repeat_buyers,
    ROUND(
        100.0 * COUNT(customer_id) /
        SUM(COUNT(customer_id)) OVER (),
        2
    ) AS percentage
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--what is the revenue contribution for each age group
select age_group,sum(purchase_amount) as Total_Revenue
from customer
group by age_group
order by Total_Revenue desc


